# Generated by Django 5.1.6 on 2025-02-19 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addscholarship_addstudent_changepassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificatestaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin')),
            ],
        ),
        migrations.CreateModel(
            name='certificatestudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin')),
            ],
        ),
        migrations.CreateModel(
            name='certificatetecher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin')),
            ],
        ),
        migrations.CreateModel(
            name='officechangepassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpassword', models.CharField(blank=True, max_length=50, null=True)),
                ('newpassword', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmpassword', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin')),
            ],
        ),
        migrations.CreateModel(
            name='staffdocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin')),
            ],
        ),
        migrations.CreateModel(
            name='studentdocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin')),
            ],
        ),
        migrations.CreateModel(
            name='techdocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin')),
            ],
        ),
        migrations.CreateModel(
            name='uploaddoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin')),
            ],
        ),
        migrations.DeleteModel(
            name='changepassword',
        ),
        migrations.DeleteModel(
            name='impcertificate',
        ),
        migrations.RenameField(
            model_name='internalupload',
            old_name='rollnumber',
            new_name='exam3',
        ),
        migrations.RemoveField(
            model_name='addscholarship',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='addscholarship',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='addscholarship',
            name='student_name',
        ),
        migrations.AddField(
            model_name='addofficestaff',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin'),
        ),
        migrations.AddField(
            model_name='addscholarship',
            name='studentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.addstudent'),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin'),
        ),
        migrations.AddField(
            model_name='addstudent',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addtechsaff',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin'),
        ),
        migrations.AddField(
            model_name='adminviewcmplt',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin'),
        ),
        migrations.AddField(
            model_name='coursemamage',
            name='DEPID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.adddepartment'),
        ),
        migrations.AddField(
            model_name='createtimetable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin'),
        ),
        migrations.AddField(
            model_name='internalupload',
            name='STUDENTID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.addstudent'),
        ),
        migrations.AddField(
            model_name='internalupload',
            name='TECHERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.addtechsaff'),
        ),
        migrations.AddField(
            model_name='internalupload',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techchangepassword',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin'),
        ),
        migrations.AddField(
            model_name='upres',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lofgin'),
        ),
        migrations.AddField(
            model_name='upres',
            name='reserch_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adddepartment',
            name='departmentstaff',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.addofficestaff'),
            preserve_default=False,
        ),
    ]
