# Generated by Django 5.1.6 on 2025-02-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_certificatestaff_certificatestudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtechsaff',
            name='choosefile',
            field=models.FileField(blank=True, null=True, upload_to='teachstafffile/'),
        ),
    ]
