# Generated by Django 5.1.6 on 2025-03-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_addtechsaff_choosefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='lofgin',
            new_name='logintable',
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('CLASS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
                ('slot_10_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_10_11', to='myapp.subject')),
                ('slot_11_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_11_12', to='myapp.subject')),
                ('slot_1_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_1_2', to='myapp.subject')),
                ('slot_2_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_2_3', to='myapp.subject')),
                ('slot_3_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_3_4', to='myapp.subject')),
                ('slot_9_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_9_10', to='myapp.subject')),
            ],
        ),
    ]
