# Generated by Django 5.1.6 on 2025-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_class_subject_rename_lofgin_logintable_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='choosefile',
            field=models.FileField(blank=True, null=True, upload_to='studentdocuments'),
        ),
    ]
