# Generated by Django 5.1.6 on 2025-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_studentdocument_choosefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
