# Generated by Django 5.1.6 on 2025-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_studentdocument_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='filename',
        ),
        migrations.AddField(
            model_name='addscholarship',
            name='deadline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addscholarship',
            name='elgibility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addscholarship',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addscholarship',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
