# Generated by Django 5.1.6 on 2025-03-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_studentdocument_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='profieimage',
            field=models.FileField(blank=True, null=True, upload_to='studentimage'),
        ),
    ]
