# Generated by Django 5.1.6 on 2025-03-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_addstudent_profieimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewdepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(blank=True, max_length=50, null=True)),
                ('departmentcode', models.CharField(blank=True, max_length=50, null=True)),
                ('departmentstaff', models.CharField(blank=True, max_length=50, null=True)),
                ('hod', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='addscholarship',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='addscholarship',
            name='elgibility',
        ),
        migrations.RemoveField(
            model_name='addscholarship',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='addscholarship',
            name='title',
        ),
        migrations.RemoveField(
            model_name='addstudent',
            name='profieimage',
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='choosefile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='uplcertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('rollnumber', models.CharField(blank=True, max_length=50, null=True)),
                ('univerregno', models.CharField(blank=True, max_length=50, null=True)),
                ('choosefile', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable')),
            ],
        ),
    ]
