# Generated by Django 5.1.7 on 2025-03-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_viewdepartment_remove_addscholarship_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addofficestaff',
            name='choosefile',
            field=models.FileField(blank=True, null=True, upload_to='offstafffile/'),
        ),
    ]
