# Generated by Django 5.1.7 on 2025-03-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_addofficestaff_choosefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartment',
            name='departmentstaff',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
