# Generated by Django 5.1.6 on 2025-03-16 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_uploaddoc_choosefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddoc',
            name='choosefile',
            field=models.FileField(blank=True, null=True, upload_to='uploadoc'),
        ),
        migrations.CreateModel(
            name='uploadce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosefile', models.FileField(blank=True, null=True, upload_to='uploadce')),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable')),
            ],
        ),
    ]
